apiVersion: "dusdjhyeon.com/v1"
kind: AutoScaler
metadata:
  name: dusdj-autoscaler
spec:
  upperBound: {{ .Values.upperBound }}
  scaleTargetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: {{ .Values.deploymentName }}
