apiVersion: batch/v1
kind: CronJob
metadata:
  name: cpu-scaling-operator-cronjob
  namespace: default
spec:
  schedule: "{{ .Values.schedule }}"
  successfulJobsHistoryLimit: 10
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: cpu-scaling-operator
            image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
            imagePullPolicy: {{ .Values.image.pullPolicy }}
          restartPolicy: OnFailure
